Fix multiple bugs in the android dev-framework.

diff --git a/tools/ant-dev b/tools/ant-dev
--- a/tools/ant-dev
+++ b/tools/ant-dev
@@ -12,22 +12,24 @@
 # source common functions and parse options
 source $(dirname ${0})/common.sh
 
+MYPID=${BASHPID}
 VER_ATTR=versionName
 FILE=AndroidManifest.xml
 [ -f ${FILE} ] || die "ERROR: ${FILE} not found. Aborting."
-VERSION_NAME=`grep ${VER_ATTR} ${FILE} | cut -d"\"" -f2`
+INIT_VERSION_NAME=`grep ${VER_ATTR} ${FILE} | cut -d"\"" -f2`
 
-[ "${VERSION_NAME}" == "" ] && die "ERROR: could not get the version name from the Android Manifest. Aborting."
+[ "${INIT_VERSION_NAME}" == "" ] && die "ERROR: could not get the version name from the Android Manifest. Aborting."
 
 # check if version name is localized
-if [ "${VERSION_NAME}" != "${VERSION_NAME/\@string\//}" ]; then
+if [ "${INIT_VERSION_NAME}" != "${INIT_VERSION_NAME/\@string\//}" ]; then
     #find the right file with the tag, and get its real value
-    FILE=`grep -r name=\"${VERSION_NAME/\@string\//}\" * | cut -d":" -f1`
-    VERSION_NAME=`grep ${VERSION_NAME/\@string\//} ${FILE} | cut -d">" -f2 | cut -d"<" -f1`
+    STRS_FILE=`grep -r name=\"${INIT_VERSION_NAME/\@string\//}\" * | cut -d":" -f1`
+    VERSION_NAME=`grep ${INIT_VERSION_NAME/\@string\//} ${STRS_FILE} | cut -d">" -f2 | cut -d"<" -f1`
 fi
 
-# escape all the / in the name
+# escape all the / in the version names
 VERSION_NAME=${VERSION_NAME/\//\\\/}
+INIT_VERSION_NAME=${INIT_VERSION_NAME/\//\\\/}
 
 # get all the info related to the git repo
 HEAD_SHA=`git log --oneline | head -n1 | cut -d" " -f1`
@@ -38,11 +40,11 @@ BRANCH_NAME=`git.branch`
 [ "`git status -s | grep -v "?? "`" != "" ] && BRANCH_NAME="${BRANCH_NAME}+dirty"
 
 # create a copy of the file before modifying it
-cp ${FILE} /tmp/ || die "ERROR: could not create a copy of ${FILE} in the /tmp folder. Aborting."
+cp ${FILE} /tmp/${FILE}-${MYPID} || die "ERROR: could not create a copy of ${FILE} in the /tmp folder. Aborting."
 
 TIME=`date +"%m-%d-%y_%H:%M"`
 # extend the version name. Format: <original_version_name>-dev-<branch_name>-<heads_sha1>-<user>-<date_time>
-sed -i -e "s/${VER_ATTR}=\"${VERSION_NAME}\"/${VER_ATTR}=\"${VERSION_NAME}-dev-${BRANCH_NAME}-${HEAD_SHA} ${USER}@${HOSTNAME} ${TIME}\"/" ${FILE} || \
+sed -i -e "s/${VER_ATTR}=\"${INIT_VERSION_NAME}\"/${VER_ATTR}=\"${VERSION_NAME}-dev-${BRANCH_NAME}-${HEAD_SHA} ${USER}@${HOSTNAME} ${TIME}\"/" ${FILE} || \
 	die "ERROR: could not extend the version name in ${FILE}. Aborting."
 
 # build the app 
@@ -50,7 +52,7 @@ ant-b $*
 RETURN=$?
 
 # restore the original file (even if the build fails)
-mv /tmp/$(basename ${FILE}) ${FILE}
+mv /tmp/$(basename ${FILE}-${MYPID}) ${FILE}
 
 # exit the script with the return value of the ant command
 exit ${RETURN}
diff --git a/tools/mesh b/tools/mesh
--- a/tools/mesh
+++ b/tools/mesh
@@ -28,10 +28,7 @@ function check_parameters () {
 
 [ -z "${MESH_ID}" -o -z "${WIFACE}" -o -z "${CHANNEL}" ] && die "ERROR: make sure that you've configured all the mesh parameters in the main config file. Aborting."
 
-[ -z "${PARAM}" ] && 
-	die "ERROR: you need to provide an action (-a <up/down>). Aborting."
-[ "${PARAM}" != "up" -a "${PARAM}" != "down" ] && 
-	die "ERROR: you need to provide an valid action (-a <up/down>). Aborting."
+[ -z "${ACTION}" ] && die "ERROR: you need to provide an action (-a <up/down>). Aborting."
 
 ip link show ${WIFACE} &>/dev/null || die "ERROR: the ${WIFACE} interface does not exist. Aborting."
 
@@ -60,6 +57,21 @@ function teardown () {
 	fi
 }
 
+#block node1 from node2 and viceversa
+# usage: block node1 node2
+function block {
+	if [ "${1}" = "" ]; then echo "block: missing nodes"; exit 1; fi
+	if [ "${2}" = "" ]; then echo "block: missing one node"; exit 1; fi
+	
+	_ID[0]=`name2id ${1}`
+	_ID[1]=`name2id ${2}`
+
+	_MAC=`name2mac ${2}`
+	adbs ${_ID[0]} shell iw dev mesh0 station set ${_MAC} plink_action block #&>/dev/null
+	_MAC=`name2mac ${1}`
+	adbs ${_ID[1]} shell iw dev mesh0 station set ${_MAC} plink_action block #&>/dev/null
+}
+
 #name of the mesh iface
 MESH_IFACE=mesh0
 NETMASK=8
@@ -68,12 +80,13 @@ MCAST_IP=225.0.0.0
 FLUSH=0
 
 # parse the incoming parameters
-usage="$0 [-a <up/down> ] [ -i <meshid> ] [ -c <channel> ] [ -f (flush) ] [ -t <ht_mode> ] [ -w <w_interface> ] [ -r <retrasnmissions/TTL> ]  [-h]"
-while getopts "a:i:c:ft:w:hr:" options; do
+usage="$0 [-a <up/down/block> ] [ -i <meshid> ] [ -c <channel> ] [ -d <devices_to_block> ] [ -f (flush) ] [ -t <ht_mode> ] [ -w <w_interface> ] [ -r <retrasnmissions/TTL> ]  [-h]"
+while getopts "a:i:c:d:ft:w:hr:" options; do
     case $options in
-	a ) PARAM=${OPTARG};;
+	a ) ACTION=${OPTARG};;
 	i ) MESH_ID=${OPTARG};;
         c ) CHANNEL=${OPTARG};;
+	d ) DEVICES=${OPTARG};;
 	f ) FLUSH=1;;
         t ) HT_MODE=${OPTARG};;
 	w ) WIFACE=${OPTARG};;
@@ -89,10 +102,30 @@ done
 #first evaluate given parameters
 check_parameters
 
-if [ ${PARAM} == "up" ]; then
+if [ ${ACTION} == "up" ]; then
 	[ ${FLUSH} -eq 1 ] && teardown
 	ip link show ${MESH_IFACE} &> /dev/null && die "ERROR: ${MESH_IFACE} interface already exists. Aborting."
 	tearup
-else
+elif [ ${ACTION} == "down" ]; then
 	teardown
+elif [ ${ACTION} == "block" ]; then
+	ip link show ${MESH_IFACE} &> /dev/null || die "ERROR: ${MESH_IFACE} interface is not up. Aborting."
+	[ -z "${DEVICES}" ] && die "ERROR: you need to provide the devices to block (-d <dev1,dev2>). Aborting."
+	DEVICES=${DEVICES//,/" "}
+	# iterate through all the devices provided
+	for dev in ${DEVICES}; do
+		_MAC=`name2mac ${dev}`
+        	#if _MAC is empty, then dev must be the mac
+	        [ -z "${_MAC}" ] && _MAC=${dev}
+		sudo iw dev ${MESH_IFACE} station set ${_MAC} plink_action block #&>/dev/null
+	done
+#This routine should go in a script that manages the android devices. For now we'll call it remote block
+elif [ ${ACTION} == "rblock" ]; then
+	ip link show ${MESH_IFACE} &> /dev/null || die "ERROR: ${MESH_IFACE} interface is not up. Aborting."
+	[ -z "${DEVICES}" ] && die "ERROR: you need to provide the devices to block (-d <dev1,dev2>). Aborting."
+	IFS=',' read -a NODES <<< "${DEVICES}"
+	echo "about to block ${NODES[0]} and ${NODES[1]}"
+	block ${NODES[0]} ${NODES[1]}
+else
+	die "ERROR: unsupported action. Aborting."
 fi
