Update builstall and logcat-p scripts
Also multiple internal changes:
  - renamed some conf variables
  - updated README instructions
  - fix some bugs
  - add some functions to common.sh

diff --git a/tools/builstall b/tools/builstall
--- a/tools/builstall
+++ b/tools/builstall
@@ -9,20 +9,41 @@
 # source common functions and parse options
 source `dirname ${0}`/common.sh
 
+# extract android:name value of tha activity with the action.MAIN intent filter
+function extractMainActivityName () {
+	i=1
+	grep -B ${i} android.intent.action.MAIN AndroidManifest.xml | grep activity &> /dev/null
+	while  [ $? -ne 0 -a ${i} -lt 100  ] ; do
+		i=$((i+1))
+		grep -B ${i} android.intent.action.MAIN AndroidManifest.xml | grep -e "<activity" &>/dev/null
+	done
+
+	[ ${i} -eq 100 ] && { echo ""; return 1; }
+
+	TST=`grep -B ${i} android.intent.action.MAIN AndroidManifest.xml | grep -v android.intent.action.MAIN | grep android:name`
+
+	#TODO: extract the value android:name properly!! Dont' commit & push this until this is FIXED!!!
+	TST=`echo ${TST} | cut -d"=" -f2`
+	echo ${TST//\"/}
+	return 0
+}
+
 BUILD_TYPE="debug"
 
 # parse the incoming parameters
-usage="$0 [ -s <device1>,<device2>.. ] [ -a ] [ -r ]  [ -h ]"
-while getopts "s:ar" options; do
+usage="$0 [ -s <device1>,<device2>.. ] [ -a ] [ -i ] [ -r ] [ -t ] [ -h ]"
+while getopts "hirs:t:" options; do
     case $options in
-	a ) DEVICES="all";;
+	i ) INSTALL="yes";;
+        r ) LAUNCH="yes";;
         s ) DEVICES=${OPTARG};;
-	r ) BUILD_TYPE="release";;
+	t ) BUILD_TYPE=${OPTARG};;
         h ) echo ${usage}
-	    echo "-s       list of devices (CB01,CB02). If "all" provided is like -a."
-            echo "-a       all connected devices"
-            echo "-r       build project in release mode"
-            echo "-h       print help"
+	    echo "-i       skip building step, just install."
+	    echo "-s       list of target devices (CB01,CB02). For all connected use \"all\"."
+            echo "-r       run the app just after installing it."
+            echo "-t       type of build: debug/release."
+            echo "-h       print this message."
             exit 1;;
         * ) echo ${usage}
             exit 1;;
@@ -38,11 +59,17 @@ else
         DEVICES=${DEVICES//,/" "}
 fi
 
+[ "${BUILD_TYPE}" != "debug" -a "${BUILD_TYPE}" != "release" ] && die "ERROR: specify a valid build type: debug/release. Aborting."
+
 # build the project
-ant-dev ${BUILD_TYPE} || exit 1
+if [ -z "${INSTALL}" ]; then
+	ant-dev ${BUILD_TYPE} || exit 1
+else
+	echo "Skip building the project..."
+fi
 
 # get the package name from the manifest
-PKG_NAME=`extract_value package AndroidManifest.xml`
+PKG_NAME=`extractAttributeXML AndroidManifest.xml /manifest package`
 
 # iterate through all the devices
 for dev in ${DEVICES}; do
@@ -56,13 +83,14 @@ for dev in ${DEVICES}; do
                 OUT=`adbs ${id} install -r ${app}`
 		# check if it failed because of inconsistent certificates.
 		if [[ "${OUT}" == *INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES* ]]; then
-			echo "[${dev}] UNINSTALLINg app....."
+			echo "[${dev}] UNINSTALLING app....."
 			OUT=`adbs ${id} uninstall ${PKG_NAME}`
 			[[ "${OUT}" == *Failure* ]] && { echo "[${dev}] ERROR: can't install ${app} (${BUILD_TYPE}). Is it a system app? Skipping device."; continue; }
 			adbs ${id} install ${app}
 		fi
-		#TODO launch the application if possible
-		# adbs ${id} shell am start -n ${PKG_NAME}/${MAIN_ACTIVITY}
-                # PROBLE: how to get the androidName of the activity with the MAIN intent filter from the AndroidManifest.xml.
+		if [ "${LAUNCH}" == "yes" ]; then
+			MAIN_ACTIVITY=`extractMainActivityName`
+			[ $? -eq 0 ] && adbs ${id} shell am start -n ${PKG_NAME}/${MAIN_ACTIVITY}
+		fi
         fi
 done
diff --git a/tools/logcat-p b/tools/logcat-p
--- a/tools/logcat-p
+++ b/tools/logcat-p
@@ -3,31 +3,30 @@
 # Source common functions and parse options
 source `dirname ${0}`/common.sh
 
-ADB_PARAMS="-s "
-
 # parse the incoming parameters
-usage="$0 [ -s <device_id> ] [ -p <package_name> ] [ -h ]"
+usage="$0 [ -s <device_name> ] [ -p <package_name> ] [ -h ]"
 while getopts "s:p:h" options; do
     case $options in
-        s ) ID=${OPTARG};;
+        s ) DEV_NAME=${OPTARG};;
         p ) PKG_NAME=${OPTARG};;
         h ) echo ${usage}
             exit 1;;
-        * ) echo ${usage}
+        * ) echo "Invalid option!"
+	    echo ${usage}
             exit 1;;
     esac
 done
 
-[ -z "${PKG_NAME}" ] && { echo "Please, provide a package name. Aborting."; echo ${usage}; exit -1; }
- 
-if [ -z "${ID}" ]; then
-	ADB_PARAMS=""
-	DEVICES=`adb devices | grep -v "List of" | grep -v '^$' -c`
-	[ ${DEVICES} -gt 1 ] && { echo "ERROR: You have more than one device connected. Please, use the -s parameter. Aborting."; echo ${usage}; exit -1; }
-fi
+[ -z "${PKG_NAME}" -a -f AndroidManifest.xml ] && PKG_NAME=`extractAttributeXML AndroidManifest.xml /manifest package`
+[ -z "${PKG_NAME}" ] && die "Please, provide a package name. ${usage}."
+[ -z "${DEV_NAME}" ] && die "Please, provide the name of device."
 
-APP_PID=`adbs ${ID} shell ps | grep ${PKG_NAME} | awk '{print $2}'`
+ID=`name2id ${DEV_NAME}`
 
-[ -z "${APP_PID}" ] && { echo "The package ${PKG_NAME} is not ins the list of running process. Launch the application first (or make sure it's the right package name). Aborting."; exit -1; }
+adbs ${ID} shell ps &> /dev/null
+[ $? -eq 1 ] && { echo ${TMP}; exit 1; }
+APP_PID=`adbs ${ID} shell ps | grep ${PKG_NAME} | grep -v "remote" | awk '{print $2}'`
 
-adbs ${ID} logcat | grep ${APP_PID}
+[ -z "${APP_PID}" ] && die "The package ${PKG_NAME} is not in the list of running process. Launch the application first (or make sure it's the right package name). Aborting."
+
+adbs ${ID} logcat | grep -e "${APP_PID}"
