Fix indentation (replace tabs with 4 white spaces).

diff --git a/tools/builstall b/tools/builstall
--- a/tools/builstall
+++ b/tools/builstall
@@ -11,21 +11,21 @@ source `dirname ${0}`/common.sh
 
 # extract android:name value of tha activity with the action.MAIN intent filter
 function extractMainActivityName () {
-	i=1
-	grep -B ${i} android.intent.action.MAIN AndroidManifest.xml | grep activity &> /dev/null
-	while  [ $? -ne 0 -a ${i} -lt 100  ] ; do
-		i=$((i+1))
-		grep -B ${i} android.intent.action.MAIN AndroidManifest.xml | grep -e "<activity" &>/dev/null
-	done
+    i=1
+    grep -B ${i} android.intent.action.MAIN AndroidManifest.xml | grep activity &> /dev/null
+    while  [ $? -ne 0 -a ${i} -lt 100  ] ; do
+        i=$((i+1))
+        grep -B ${i} android.intent.action.MAIN AndroidManifest.xml | grep -e "<activity" &>/dev/null
+    done
 
-	[ ${i} -eq 100 ] && { echo ""; return 1; }
+    [ ${i} -eq 100 ] && { echo ""; return 1; }
 
-	TST=`grep -B ${i} android.intent.action.MAIN AndroidManifest.xml | grep -v android.intent.action.MAIN | grep android:name`
+    TST=`grep -B ${i} android.intent.action.MAIN AndroidManifest.xml | grep -v android.intent.action.MAIN | grep android:name`
 
-	#TODO: extract the value android:name properly!! Dont' commit & push this until this is FIXED!!!
-	TST=`echo ${TST} | cut -d"=" -f2`
-	echo ${TST//\"/}
-	return 0
+    #TODO: extract the value android:name properly!! Dont' commit & push this until this is FIXED!!!
+    TST=`echo ${TST} | cut -d"=" -f2`
+    echo ${TST//\"/}
+    return 0
 }
 
 BUILD_TYPE="debug"
@@ -34,13 +34,13 @@ BUILD_TYPE="debug"
 usage="$0 [ -s <device1>,<device2>.. ] [ -a ] [ -i ] [ -r ] [ -t ] [ -h ]"
 while getopts "hirs:t:" options; do
     case $options in
-	i ) INSTALL="yes";;
+        i ) INSTALL="yes";;
         r ) LAUNCH="yes";;
         s ) DEVICES=${OPTARG};;
-	t ) BUILD_TYPE=${OPTARG};;
+        t ) BUILD_TYPE=${OPTARG};;
         h ) echo ${usage}
-	    echo "-i       skip building step, just install."
-	    echo "-s       list of target devices (-s CB1,CB2:CB8,CB15:CB20,CB99). For all connected use \"all\"."
+            echo "-i       skip building step, just install."
+            echo "-s       list of target devices (-s CB1,CB2:CB8,CB15:CB20,CB99). For all connected use \"all\"."
             echo "-r       run the app just after installing it."
             echo "-t       type of build: debug/release."
             echo "-h       print this message."
@@ -57,9 +57,9 @@ validate_dev_name_list ${DEVICES} || die "ERROR: the list of input devices is no
 
 # build the project
 if [ -z "${INSTALL}" ]; then
-	ant-dev ${BUILD_TYPE} || exit 1
+    ant-dev ${BUILD_TYPE} || exit 1
 else
-	echo "Skip building the project..."
+    echo "Skip building the project..."
 fi
 
 # get the package name from the manifest
@@ -67,19 +67,19 @@ PKG_NAME=`extractAttributeXML AndroidManifest.xml /manifest package`
 
 # iterate through all the devices
 for dev in ${DEVICES}; do
-	id=`name2id ${dev}`
-	app=`ls bin/*-${BUILD_TYPE}.apk`
-	echo "[${dev}] Installing ${app} (${BUILD_TYPE} version)..."
-	OUT=`adb_agnostic ${id} install -r ${app}`
-	# check if it failed because of inconsistent certificates.
-	if [[ "${OUT}" == *INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES* ]]; then
-		echo "[${dev}] UNINSTALLING app....."
-		OUT=`adb_agnostic ${id} uninstall ${PKG_NAME}`
-		[[ "${OUT}" == *Failure* ]] && { echo "[${dev}] ERROR: can't install ${app} (${BUILD_TYPE}). Is it a system app? Skipping device."; continue; }
-		adb_agnostic ${id} install ${app}
-	fi
-	if [ "${LAUNCH}" == "yes" ]; then
-		MAIN_ACTIVITY=`extractMainActivityName`
-		[ $? -eq 0 ] && adb_agnostic ${id} shell am start -n ${PKG_NAME}/${MAIN_ACTIVITY}
-	fi
+    id=`name2id ${dev}`
+    app=`ls bin/*-${BUILD_TYPE}.apk`
+    echo "[${dev}] Installing ${app} (${BUILD_TYPE} version)..."
+    OUT=`adb_agnostic ${id} install -r ${app}`
+    # check if it failed because of inconsistent certificates.
+    if [[ "${OUT}" == *INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES* ]]; then
+        echo "[${dev}] UNINSTALLING app....."
+        OUT=`adb_agnostic ${id} uninstall ${PKG_NAME}`
+        [[ "${OUT}" == *Failure* ]] && { echo "[${dev}] ERROR: can't install ${app} (${BUILD_TYPE}). Is it a system app? Skipping device."; continue; }
+        adb_agnostic ${id} install ${app}
+    fi
+    if [ "${LAUNCH}" == "yes" ]; then
+        MAIN_ACTIVITY=`extractMainActivityName`
+        [ $? -eq 0 ] && adb_agnostic ${id} shell am start -n ${PKG_NAME}/${MAIN_ACTIVITY}
+    fi
 done
diff --git a/tools/mesh b/tools/mesh
--- a/tools/mesh
+++ b/tools/mesh
@@ -25,51 +25,47 @@ source $(dirname ${0})/common.sh
 
 # check that all the needed parameters are valid
 function check_parameters () {
-
-[ -z "${MESH_ID}" -o -z "${WIFACE}" -o -z "${CHANNEL}" ] && die "ERROR: make sure that you've configured all the mesh parameters in the main config file. Aborting."
-
-[ -z "${ACTION}" ] && die "ERROR: you need to provide an action (-a <up/down>). Aborting."
-
-ip link show ${WIFACE} &>/dev/null || die "ERROR: the ${WIFACE} interface does not exist. Aborting."
-
+    [ -z "${MESH_ID}" -o -z "${WIFACE}" -o -z "${CHANNEL}" ] && die "ERROR: make sure that you've configured all the mesh parameters in the main config file. Aborting."
+    [ -z "${ACTION}" ] && die "ERROR: you need to provide an action (-a <up/down>). Aborting."
+    ip link show ${WIFACE} &>/dev/null || die "ERROR: the ${WIFACE} interface does not exist. Aborting."
 }
 
 function tearup () {
-	sudo iw ${WIFACE} interface add ${MESH_IFACE} type mesh || \
-		 die "ERROR: problem when creating the mesh interface on ${WIFACE}. Is your machine mesh enabled? Please, read the comments within this script for more info. Aborting."
-	sudo ip link set dev ${WIFACE} down &> /dev/null
-	sudo iw ${MESH_IFACE} set channel ${CHANNEL} ${HT_MODE} || die "ERROR: problem when setting the channel. Aborting."
-	LOCAL_IP=`mac2ip $(if2mac ${WIFACE})`
-	sudo ip address add dev ${MESH_IFACE} ${LOCAL_IP}/${NETMASK} broadcast ${BCAST_IP} || \
-		die "ERROR: problem when configuring the ${MESH_IFACE} interface. Aborting." 
-	sudo ip link set dev ${MESH_IFACE} up || die "ERROR: problem when bringing the ${MESH_IFACE} interface up. Aborting."
-	[ -n  "${TTL}" ] && sudo iw dev ${MESH_IFACE} set mesh_param mesh_ttl ${TTL}
-	sudo iw ${MESH_IFACE} mesh join ${MESH_ID} vendor_sync on || die "ERROR: problem joining the mesh ${MESH_ID}. Aborting."
+    sudo iw ${WIFACE} interface add ${MESH_IFACE} type mesh || \
+        die "ERROR: problem when creating the mesh interface on ${WIFACE}. Is your machine mesh enabled? Please, read the comments within this script for more info. Aborting."
+    sudo ip link set dev ${WIFACE} down &> /dev/null
+    sudo iw ${MESH_IFACE} set channel ${CHANNEL} ${HT_MODE} || die "ERROR: problem when setting the channel. Aborting."
+    LOCAL_IP=`mac2ip $(if2mac ${WIFACE})`
+    sudo ip address add dev ${MESH_IFACE} ${LOCAL_IP}/${NETMASK} broadcast ${BCAST_IP} || \
+        die "ERROR: problem when configuring the ${MESH_IFACE} interface. Aborting." 
+    sudo ip link set dev ${MESH_IFACE} up || die "ERROR: problem when bringing the ${MESH_IFACE} interface up. Aborting."
+    [ -n  "${TTL}" ] && sudo iw dev ${MESH_IFACE} set mesh_param mesh_ttl ${TTL}
+    sudo iw ${MESH_IFACE} mesh join ${MESH_ID} vendor_sync on || die "ERROR: problem joining the mesh ${MESH_ID}. Aborting."
 }
 
 function teardown () {
-	ip link show ${MESH_IFACE} &> /dev/null
-	if [ $? -eq 0 ]; then
-                sudo ip link set dev ${MESH_IFACE} down &> /dev/null || \
-			 die "ERROR: problem when bringing down the ${MESH_IFACE} interface. Aborting."
-                sudo iw dev ${MESH_IFACE} del &> /dev/null || \
-			die "ERROR: problem when deleting the ${MESH_IFACE} interface. Aborting."
-	fi
+    ip link show ${MESH_IFACE} &> /dev/null
+    if [ $? -eq 0 ]; then
+        sudo ip link set dev ${MESH_IFACE} down &> /dev/null || \
+            die "ERROR: problem when bringing down the ${MESH_IFACE} interface. Aborting."
+        sudo iw dev ${MESH_IFACE} del &> /dev/null || \
+            die "ERROR: problem when deleting the ${MESH_IFACE} interface. Aborting."
+    fi
 }
 
 #block node1 from node2 and viceversa
 # usage: block node1 node2
 function block {
-	if [ "${1}" = "" ]; then echo "block: missing nodes"; exit 1; fi
-	if [ "${2}" = "" ]; then echo "block: missing one node"; exit 1; fi
-	
-	_ID[0]=`name2id ${1}`
-	_ID[1]=`name2id ${2}`
+    if [ "${1}" = "" ]; then echo "block: missing nodes"; exit 1; fi
+    if [ "${2}" = "" ]; then echo "block: missing one node"; exit 1; fi
 
-	_MAC=`name2mac ${2}`
-	adb_agnostic ${_ID[0]} shell iw dev mesh0 station set ${_MAC} plink_action block #&>/dev/null
-	_MAC=`name2mac ${1}`
-	adb_agnostic ${_ID[1]} shell iw dev mesh0 station set ${_MAC} plink_action block #&>/dev/null
+    _ID[0]=`name2id ${1}`
+    _ID[1]=`name2id ${2}`
+
+    _MAC=`name2mac ${2}`
+    adb_agnostic ${_ID[0]} shell iw dev mesh0 station set ${_MAC} plink_action block #&>/dev/null
+    _MAC=`name2mac ${1}`
+    adb_agnostic ${_ID[1]} shell iw dev mesh0 station set ${_MAC} plink_action block #&>/dev/null
 }
 
 #name of the mesh iface
@@ -83,18 +79,18 @@ FLUSH=0
 usage="$0 [-a <up/down/block> ] [ -i <meshid> ] [ -c <channel> ] [ -d <devices_to_block> ] [ -f (flush) ] [ -t <ht_mode> ] [ -w <w_interface> ] [ -r <retrasnmissions/TTL> ]  [-h]"
 while getopts "a:i:c:d:ft:w:hr:" options; do
     case $options in
-	a ) ACTION=${OPTARG};;
-	i ) MESH_ID=${OPTARG};;
+        a ) ACTION=${OPTARG};;
+        i ) MESH_ID=${OPTARG};;
         c ) CHANNEL=${OPTARG};;
-	d ) DEVICES=${OPTARG};;
-	f ) FLUSH=1;;
+        d ) DEVICES=${OPTARG};;
+        f ) FLUSH=1;;
         t ) HT_MODE=${OPTARG};;
-	w ) WIFACE=${OPTARG};;
-	r ) TTL=${OPTARG};;
+        w ) WIFACE=${OPTARG};;
+        r ) TTL=${OPTARG};;
         h ) echo ${usage}
             exit 1;;
         * ) echo this is the option: ${option}
-	    echo ${usage}
+            echo ${usage}
             exit 1;;
     esac
 done
@@ -103,29 +99,29 @@ done
 check_parameters
 
 if [ ${ACTION} == "up" ]; then
-	[ ${FLUSH} -eq 1 ] && teardown
-	ip link show ${MESH_IFACE} &> /dev/null && die "ERROR: ${MESH_IFACE} interface already exists. Aborting."
-	tearup
+    [ ${FLUSH} -eq 1 ] && teardown
+    ip link show ${MESH_IFACE} &> /dev/null && die "ERROR: ${MESH_IFACE} interface already exists. Aborting."
+    tearup
 elif [ ${ACTION} == "down" ]; then
-	teardown
+    teardown
 elif [ ${ACTION} == "block" ]; then
-	ip link show ${MESH_IFACE} &> /dev/null || die "ERROR: ${MESH_IFACE} interface is not up. Aborting."
-	[ -z "${DEVICES}" ] && die "ERROR: you need to provide the devices to block (-d <dev1,dev2>). Aborting."
-	DEVICES=${DEVICES//,/" "}
-	# iterate through all the devices provided
-	for dev in ${DEVICES}; do
-		_MAC=`name2mac ${dev}`
-        	#if _MAC is empty, then dev must be the mac
-	        [ -z "${_MAC}" ] && _MAC=${dev}
-		sudo iw dev ${MESH_IFACE} station set ${_MAC} plink_action block #&>/dev/null
-	done
-#This routine should go in a script that manages the android devices. For now we'll call it remote block
+    ip link show ${MESH_IFACE} &> /dev/null || die "ERROR: ${MESH_IFACE} interface is not up. Aborting."
+    [ -z "${DEVICES}" ] && die "ERROR: you need to provide the devices to block (-d <dev1,dev2>). Aborting."
+    DEVICES=${DEVICES//,/" "}
+    # iterate through all the devices provided
+    for dev in ${DEVICES}; do
+        _MAC=`name2mac ${dev}`
+        #if _MAC is empty, then dev must be the mac
+        [ -z "${_MAC}" ] && _MAC=${dev}
+        sudo iw dev ${MESH_IFACE} station set ${_MAC} plink_action block #&>/dev/null
+    done
+    #This routine should go in a script that manages the android devices. For now we'll call it remote block
 elif [ ${ACTION} == "rblock" ]; then
-	ip link show ${MESH_IFACE} &> /dev/null || die "ERROR: ${MESH_IFACE} interface is not up. Aborting."
-	[ -z "${DEVICES}" ] && die "ERROR: you need to provide the devices to block (-d <dev1,dev2>). Aborting."
-	IFS=',' read -a NODES <<< "${DEVICES}"
-	echo "about to block ${NODES[0]} and ${NODES[1]}"
-	block ${NODES[0]} ${NODES[1]}
+    ip link show ${MESH_IFACE} &> /dev/null || die "ERROR: ${MESH_IFACE} interface is not up. Aborting."
+    [ -z "${DEVICES}" ] && die "ERROR: you need to provide the devices to block (-d <dev1,dev2>). Aborting."
+    IFS=',' read -a NODES <<< "${DEVICES}"
+    echo "about to block ${NODES[0]} and ${NODES[1]}"
+    block ${NODES[0]} ${NODES[1]}
 else
-	die "ERROR: unsupported action. Aborting."
+    die "ERROR: unsupported action. Aborting."
 fi
